### PR TITLE
Login Page.Issue no.(#4)

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Live link:
https://anupam-dagar.github.io/FaceMe-test/login.html

### CODE REVIEW

**Comment by Trailblazerr1** [comment]
In the middle there should be a login with facebook button. Move the simple login button to the right corner.

**Comment by Anupam-dagar** [comment]
Ok,  I got it. 
Will update it by tomorrow.

**Comment by Anupam-dagar** [comment]
Required changes has been done.

**Comment by Trailblazerr1** [comment]
Pull requests aren't being accepted for this project right now. Wait till things sort out.

**Comment by Anupam-dagar** [comment]
Is the page ok now?

**Comment by gauthamzz** [comment]
@Trailblazerr1 please add your project to projects,yml in opencodecollab and merge the pr

**Review by gauthamzz — APPROVED** [review]

**Pull request merged**
